version: "3.7"
services:
  psql:
    image: postgres:12-alpine
    volumes:
      - ./psql-data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_USER: "todo"
      POSTGRES_PASSWORD: "MriwKRj83XVYwzM2"
    ports:
      - "5432:5432"

